import { Recipe } from "../models/recipe";

export const recipes: Recipe[] = [
    {
        id: '1',
        name: 'Lasagna',
        description: 'Lasagna is an Italian dish made of stacked layers of thin flat pasta alternating with fillings such as ragù, cheese, vegetables, and seasonings. It is a traditional dish of central and northern Italy, and is also popular in the United States and Canada. The dish is made by layering sheets of pasta alternately with fillings such as ragù, cheese, vegetables, and seasonings, and baking or steaming it until the pasta is cooked and the filling is hot. The dish is traditionally baked in an oven, but may also be prepared in a slow cooker or pressure cooker. The dish is traditionally made with a meat ragù, but may also be made with vegetables, fish, or cheese.',
        ingredients: [],
        instructions: [],
        image: 'https://picsum.photos/200',
        calories: 0,
        fat: 0,
        carbs: 0,
        protein: 0,
        cholesterol: 0,
        sodium: 0,
        fiber: 0,
        sugar: 0,
        saturatedFat: 0,
        transFat: 0,
        unsaturatedFat: 0,
        cookTime: 0,
        prepTime: 0,
        totalTime: 0,
        servings: 0,
        source: '',
        sourceUrl: '',
        created: new Date(),
        updated: new Date(),
        tags: [],
    },
    {
        id: '2',
        name: 'Spaghetti Aglio e Olio',
        description: 'Spaghetti aglio e olio (Italian pronunciation: [spaˈɡetti aʎˈʎo e ˈɔːljo], "spaghetti with garlic and oil") is a simple Italian pasta dish. It is made with spaghetti, garlic, olive oil, and chili pepper. It is a traditional dish of the Campania region, and is popular throughout Italy. It is often served as a first course, but may also be served as a second course. It is traditionally made with spaghetti, but may also be made with other pasta shapes. It is traditionally made with garlic, olive oil, and chili pepper, but may also be made with other ingredients such as anchovies, tomatoes, and basil. It is traditionally served with grated cheese, but may also be served with other toppings such as grated cheese, grated Parmesan cheese, or grated Pecorino cheese.',
        ingredients: [],
        instructions: [],
        image: 'https://picsum.photos/200',
        calories: 0,
        fat: 0,
        carbs: 0,
        protein: 0,
        cholesterol: 0,
        sodium: 0,
        fiber: 0,
        sugar: 0,
        saturatedFat: 0,
        transFat: 0,
        unsaturatedFat: 0,
        cookTime: 0,
        prepTime: 0,
        totalTime: 0,
        servings: 0,
        source: '',
        sourceUrl: '',
        created: new Date(),
        updated: new Date(),
        tags: [],
    },
    {
        id: '3',
        name: 'Spaghetti Carbonara',
        description: 'Spaghetti carbonara is a pasta dish from Rome made with egg, hard cheese, cured pork, and black pepper. It is a traditional dish of the Roman cuisine, and is popular throughout Italy. It is often served as a first course, but may also be served as a second course. It is traditionally made with spaghetti, but may also be made with other pasta shapes. It is traditionally made with egg, hard cheese, cured pork, and black pepper, but may also be made with other ingredients such as cream, vegetables, and herbs. It is traditionally served with grated cheese, but may also be served with other toppings such as grated cheese, grated Parmesan cheese, or grated Pecorino cheese.',
        ingredients: [],
        instructions: [],
        image: 'https://picsum.photos/200',
        calories: 0,
        fat: 0,
        carbs: 0,
        protein: 0,
        cholesterol: 0,
        sodium: 0,
        fiber: 0,
        sugar: 0,
        saturatedFat: 0,
        transFat: 0,
        unsaturatedFat: 0,
        cookTime: 0,
        prepTime: 0,
        totalTime: 0,
        servings: 0,
        source: '',
        sourceUrl: '',
        created: new Date(),
        updated: new Date(),
        tags: [],
    },
    {
        id: '4',
        name: 'Spaghetti Bolognese',
        description: 'Spaghetti Bolognese is a pasta dish from Bologna made with meat sauce and Parmesan cheese. It is a traditional dish of the Emilia-Romagna region, and is popular throughout Italy. It is often served as a first course, but may also be served as a second course. It is traditionally made with spaghetti, but may also be made with other pasta shapes. It is traditionally made with meat sauce and Parmesan cheese, but may also be made with other ingredients such as vegetables, herbs, and spices. It is traditionally served with grated cheese, but may also be served with other toppings such as grated cheese, grated Parmesan cheese, or grated Pecorino cheese.',
        ingredients: [
            {
                id: '1',
                name: 'Spaghetti',
                amount: 500,
                unit: 'grams',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '2',
                name: 'Ground Beef',
                amount: 500,
                unit: 'grams',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '3',
                name: 'Onion',
                amount: 1,
                unit: 'unit',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '4',
                name: 'Garlic',
                amount: 2,
                unit: 'cloves',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '5',
                name: 'Tomato Paste',
                amount: 1,
                unit: 'can',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '6',
                name: 'Tomato Sauce',
                amount: 1,
                unit: 'can',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '7',
                name: 'Oregano',
                amount: 1,
                unit: 'teaspoon',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '8',
                name: 'Salt',
                amount: 1,
                unit: 'teaspoon',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '9',
                name: 'Pepper',
                amount: 1,
                unit: 'teaspoon',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
            {
                id: '10',
                name: 'Parmesan Cheese',
                amount: 1,
                unit: 'cup',
                created: new Date(),
                updated: new Date(),
                recipeId: '4',
            },
        ],
        instructions: [
            {
                id: '1',
                text: 'Cook the pasta according to the package directions. Drain and set aside.',
                recipeId: '4',
                created: new Date(),
                updated: new Date(),
                step: 1,
            },
            {
                id: '2',
                text: 'In a large skillet, cook the ground beef, onion, and garlic over medium heat until meat is no longer pink; drain. Stir in the tomatoes, tomato sauce, tomato paste, sugar, salt, Italian seasoning, and pepper. Bring to a boil. Reduce heat; simmer, uncovered, for 10-15 minutes or until thickened.',
                recipeId: '4',
                created: new Date(),
                updated: new Date(),
                step: 2,
            },
            {
                id: '3',
                text: 'Stir in the cooked pasta and Parmesan cheese. Serve immediately.',
                recipeId: '4',
                created: new Date(),
                updated: new Date(),
                step: 3,
            },
        ],
        image: 'https://picsum.photos/200',
        calories: 0,
        fat: 0,
        carbs: 0,
        protein: 0,
        cholesterol: 0,
        sodium: 0,
        fiber: 0,
        sugar: 0,
        saturatedFat: 0,
        transFat: 0,
        unsaturatedFat: 0,
        cookTime: 0,
        prepTime: 0,
        totalTime: 0,
        servings: 0,
        source: '',
        sourceUrl: '',
        created: new Date(),
        updated: new Date(),
        tags: [
            {
                id: '1',
                name: 'Italian',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: '2',
                name: 'Pasta',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: '3',
                name: 'Beef',
                created: new Date(),
                updated: new Date(),
            },
        ],
    },
    {
        id: '5',
        name: 'Spaghetti alla Puttanesca',
        description: 'Spaghetti alla puttanesca is a pasta dish from Naples made with tomatoes, garlic, and anchovies. It is a traditional dish of the Campania region, and is popular throughout Italy. It is often served as a first course, but may also be served as a second course. It is traditionally made with spaghetti, but may also be made with other pasta shapes. It is traditionally made with tomatoes, garlic, and anchovies, but may also be made with other ingredients such as vegetables, herbs, and spices. It is traditionally served with grated cheese, but may also be served with other toppings such as grated cheese, grated Parmesan cheese, or grated Pecorino cheese.',
        ingredients: [],
        instructions: [],
        image: 'https://picsum.photos/200',
        calories: 0,
        fat: 0,
        carbs: 0,
        protein: 0,
        cholesterol: 0,
        sodium: 0,
        fiber: 0,
        sugar: 0,
        saturatedFat: 0,
        transFat: 0,
        unsaturatedFat: 0,
        cookTime: 0,
        prepTime: 0,
        totalTime: 0,
        servings: 0,
        source: '',
        sourceUrl: '',
        created: new Date(),
        updated: new Date(),
        tags: [],
    },
];